sudo: false
language: c

addons:
  apt:
    packages:
    - pandoc

branches:
  only:
  - /^\d+?-?\w+?$/

env:
  global:
  - secure: Sp/oFmTZ+cDRZj6QlHSXXLMdNy6kPtCXp51uacNrUWaVKRB+3fE/MsG9HO/DO3oZPdYJ87f9kR078lYbiIsDmxBDWNEa54BRuXjnR9esqeZtuPoweiSWbsdA15TcdvWcwR9sxhMmlHBNG2qX8j0flnv0sYd3LeA3zaFX2RTdU4gLUCSwuibjtMH4EBMtT0pRMPCkU7+kNwtPUv1fY8091tDHlqONO84QlKep7TuULs+/kSFOijTivKMdjq7tmIncudyeX2jmYpG3Hicwg8hEvMzPygLkObOssWFuIJtYddiMDhgeUEymnfPlkyx+k6Ch1eGMCfilgskQSRhWQwe11DjCd7Zllp1WrkYF8710VgHcxgLwMraTlHXcP+oXT7ZmnZB9Q7waxH8ix/u7pElQzfTHPBeVTmY/QQ5wKmyYEyutZVcIbxerygo4v0rcqZdqkxUSOb+Y5hWLq+CgX6h/M6kVn69ce++Cju5PUEz79V2lpyII1EBH1XCbanta8YWhtQdNbSrjQc3nUZuco+Cb+o8uIvBXd2aDjyoxGFiuMYyjowaBOIlcBP6YLlXQLajDO1DHVSzYLMm1MBKhmu2Ucb+WIFZOtnRVw6hOuNX6KYa4pWkGaLyF6s8Xi7Sz64yqEf7mlEe5aO4ioZ7iMsknfDKNvax7VcacIhjM7ZBXIaA=
  - secure: nMkHewvE4+rwtCkYNVYS6iazXMx7nOuf7c05J7ieTOdqGO7W/5BRRz16bMk/cz6LgP4GSW2H4m2/CBUnebaXQCX+J6mI7WOZjrMMnFtlSNGrW+nuDOfox1p57DeElSdMtqfsuppZukdZrS01Lg/P98WxiZRjARR2xKh2XIA1cD/v6Xdd977ig1Fo557/a+iiyvaMRcZ20MLQYpz3SJsduPLOEMWXdFlNxT8EbtsyEIt1CyzSPlr8sgEFxOq6qn8N+zG9d8deL6LH1iqCFg0lfOuFdCJRirs+m6kyLCIOmWHUg9R5iVzRr17SPLfZU5f1fI9ZfWeTKKeVyZ+cOpXwsxIy7wbqwviN5QUeR3qtxS5U+mk+gMNNpbL6dNEvBBpLEvdoD3v4aPxp0amfZehUACEpKpIpS82ppCBVZVizKJru1wf0gWbfqj5GsUQy34RdwuWfyQJomsh2ECOAQ9LBjgyWmKfLwYrSwAehQeL7pNzWqQE99ffLCt4Y1Btiw5kSQkIGsvpLoVtaagcOvs57IqHzGmwj9LgKuYr+iX3RoR1viR2ayQ6OCll5NBaGFD2ebWA2aat+H2hWf12zJY+zcI5fT1Wg9gkUYnu7d7JnKjT2eMorNuCiEgwKdWlgVnZoy4V0Jguo396zvP0swZBLadHz4vuoW1URP7s4Y8MGdVA=

script: curl -s https://raw.githubusercontent.com/oUF-wow/packager/master/release.sh | bash

notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      secure: wsogdEVI1VOjhZaaqTPj174byvV2UzPKozQf6YM4X03ywg/s87rm9BEHyDB7qVKPJjkPzFN2i8n4s4oLdYW/1quA2xXMq+cLpX9Mf92CMstOU7Q6xQ0yGNkKVx/c4rID3OXdrWEr7tPgdvlS5DWpgV5V1Ha2LYMpIkB7Tvk2MTLppMgVsu+uxymqaJwWn4W65LRlenANbh6MO1afEB0z2I8XcSS/loysXSNYO4vuv8hHSTdRErA8leoLn8YQvmD2oKSVLi+9TPa9ZQ3weqVSl+mFF/o+vQSKA5h4FWnhZ1FIYQcpN2HeTZuFLf9RLEOfhi1dqvK5rfTaheATDINUtX55/DvVAIYLFYQ3rxTKRBNc/7SmZE7BrCx6gp4aLr3k2LO7d8zI0MbEmom3tTJg61DQZHjN33SsMgH5LgC6T/gSLe3cKcB2WdsGEev+b+Lmz6gFSNqk68EKypZmUSW83Me5FukIEzCmhUAtL6YUdhKbBdfMDOp4Za2enkwfk2Y85+OVZL8PQGvCV7Ue3eg8Arw1K7Po8K398krewqu8V2ix7NvC4QIyqokT65Knz/diSrti2J8irhks3umedwRhUntR6Wqwk5qGuoCyyAlSEA7HrpR6gqxS1h/CpDy+8VnV4GDIVkCb7ityb09Ptqy9j+hjh3M91174LRaYlDH/GoI=
